apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildkit
  namespace: build 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buildkit
  template:
    metadata:
      labels:
        app: buildkit
    spec:
      containers:
      - name: buildkitd
        image: moby/buildkit:latest
        command: 
          - "/bin/sh"
          - "-c"
          - |
            buildkitd --addr tcp://0.0.0.0:1234 &
            wait
        ports:
        - containerPort: 1234
          name: buildkit
---
apiVersion: v1
kind: Service
metadata:
  name: buildkit
  namespace: build
spec:
  selector:
    app: buildkit
  ports:
    - protocol: TCP
      port: 1234
      targetPort: 1234
