apiVersion: apps/v1
kind: Deployment
metadata:
  name: copa
  namespace: security
spec:
  replicas: 1
  selector:
    matchLabels:
      app: copa
  template:
    metadata:
      labels:
        app: copa
    spec:
      containers:
      - name: copa
        image: ghcr.io/project-copacetic/copa-action:v0.6.2
        # Add necessary resource limits and environment variables
        env:
          - name: TRIVY_SERVER_URL
            value: "http://trivy.security.svc.cluster.local
